from enum import Enum
#list of majors at Texas State associated with a number
#This Enum will be used to classify the buildings ans question to respective majors
class Majors(Enum):
    ACCOUNTING = 1
    AGRICULTURE = 2
    ANTHROPOLOGY = 3
    ART = 4
    HISTORY = 5
    BIOLOGY = 6
    CHEMISTRY = 7
    COMPUTER_SCIENCE = 8
    CRIMINAL_JUSTICE = 9
    DANCE = 10
    ECONOMICS = 11
    ELECTRICAL_ENGINEERING = 12
    ENGLISH = 13
    EXERCISE_AND_SPORTS_SCIENCE = 14
    FOREIGN_LANGUAGES = 15
    GEOGRAPHY = 16
    HISTORY = 17
    INDUSTRIAL_ENGINEERING = 18
    INTERNATIONAL_RELATIONS = 19
    JOURNALISM_AND_MASS_COMMUNICATION = 20
    MANAGEMENT = 21
    MANUFACTURING_ENGINEERING = 22
    MARKETING = 23
    MASS_COMMUNICATION = 24
    MATHEMATICS = 25
    MUSIC = 26
    NURSING = 27
    NUTRITION_AND_FOODS = 28
    PHILOSOPHY = 29
    PHOTOGRAPHY = 30
    PHYSICS = 31
    POLITICAL_SCIENCE = 32
    PSYCHOLOGY = 33
    RADIATION_THERAPY = 34
    SOCIOLOGY = 35