from enum import Enum
#list of majors at Texas State associated with a number
#This Enum will be used to classify the buildings ans question to respective majors
class Majors(Enum):
    NEUTRAL = 0
    ACCOUNTING = 1
    AGRICULTURE = 2
    ANTHROPOLOGY = 3
    ART = 4
    BIOLOGY = 5
    CHEMISTRY = 6
    COMPUTER_SCIENCE = 7
    CRIMINAL_JUSTICE = 8
    DANCE = 9
    ECONOMICS = 10
    ELECTRICAL_ENGINEERING = 11
    ENGLISH = 12
    EXERCISE_AND_SPORTS_SCIENCE = 13
    FOREIGN_LANGUAGES = 14
    GEOGRAPHY = 15
    HISTORY = 16
    INDUSTRIAL_ENGINEERING = 17
    INTERNATIONAL_RELATIONS = 18
    JOURNALISM_AND_MASS_COMMUNICATION = 19
    MANAGEMENT = 20
    MANUFACTURING_ENGINEERING = 21
    MARKETING = 22
    MASS_COMMUNICATION = 23
    MATHEMATICS = 24
    MUSIC = 25
    NURSING = 26
    NUTRITION_AND_FOODS = 27
    PHILOSOPHY = 28
    PHOTOGRAPHY = 29
    PHYSICS = 30
    POLITICAL_SCIENCE = 31
    PSYCHOLOGY = 32
    RADIATION_THERAPY = 33
    SOCIOLOGY = 34